#dev （Development environment） ： 开发环境，外部用户无法访问，开发人员使用，版本变动很大。
#sit(System Integration Test ): 系统集成测试，开发人员自己测试流程是否走通。
#test: 测试环境，外部用户无法访问，专门给测试人员使用的，版本相对稳定。
#fat (Feature Acceptance Test environment) : 功能验收测试环境，用于软件测试者测试使用
#uat(User Acceptance Test environment): 用户验收测试环境，用于生产环境下的软件测试者测试使用。
#pre ：灰度环境，外部用户可以访问，但是服务器配置相对低，其它和生产一样，外部用户可以访问，版本发布初期，正式版本发布前。
#pro（Production environment）：生产环境，面向外部用户的环境，正式环境，连接上互联网即可访问。
spring:
  profiles:
    active: dev3
jasypt:
  encryptor:
    password: password
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

